insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (1, 'Lamb - Bones', 'Ext carot art lig-epist', false, 20.6, 952, 1);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (2, 'Sobe - Tropical Energy', 'Arth/pros rem wo re-wrst', false, 44.6, 554, 2);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (3, 'Rye Special Old', 'Tarsal tunnel release', false, 21.5, 542, 3);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (4, 'Galliano', 'Cystocel/rectocel repair', true, 8.1, 572, 4);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (5, 'Veal - Inside', 'Revision of tracheostomy', true, 24.7, 916, 5);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (6, 'Garbage Bag - Clear', 'Metacarp/carp sequestrec', true, 17.9, 718, 6);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (7, 'Pork - Smoked Back Bacon', 'Inf liquid brachy isotop', false, 37.2, 752, 7);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (8, 'Bulgar', 'Excision of vessel NOS', true, 13.8, 629, 8);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (9, 'Bread Crumbs - Panko', 'Vasectomy', false, 34.2, 966, 9);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (10, 'Soup - Knorr, Veg / Beef', 'Arthrodesis of elbow', true, 9.1, 520, 10);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (11, 'Pecan Raisin - Tarts', 'Activ musculosk exer NEC', false, 28.5, 777, 11);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (12, 'Appetizer - Smoked Salmon / Dill', 'Unilat exten simp mastec', true, 41.7, 590, 12);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (13, 'Vector Energy Bar', 'Elevate skull fx fragmnt', true, 33.1, 674, 13);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (14, 'Flower - Commercial Bronze', 'Urethroves junct plicat', true, 47.9, 820, 14);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (15, 'Bacardi Raspberry', 'Uterine art emb w/o coil', true, 45.8, 714, 15);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (16, 'Pepsi - Diet, 355 Ml', 'Micro exam-lower GI NEC', true, 39.9, 551, 16);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (17, 'Goat - Whole Cut', 'Clos cereb meninges bx', true, 47.4, 982, 17);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (18, 'Lemonade - Black Cherry, 591 Ml', 'Anterior chamber op NEC', true, 49.7, 728, 18);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (19, 'Duck - Breast', 'Occlude abd vein NEC', true, 39.5, 551, 19);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (20, 'Tea - English Breakfast', 'Culdoscopy', true, 8.9, 905, 20);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (21, 'Salt And Pepper Mix - Black', 'Evac ob hemat vulva/vag', false, 20.5, 591, 21);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (22, 'Thyme - Dried', 'Epikeratophakia', false, 4.2, 630, 22);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (23, 'Mushroom - Chantrelle, Fresh', 'Remov ureteral drain', true, 18.4, 873, 23);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (24, 'Garlic - Elephant', 'Lt heart angiocardiogram', true, 26.4, 841, 24);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (25, 'Onions - Vidalia', 'Cardiotomy', true, 50.0, 654, 25);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (26, 'Tilapia - Fillets', 'Muscle or fascia graft', false, 13.3, 866, 26);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (27, 'Bread - 10 Grain Parisian', 'Tot rep truncus arterios', false, 35.3, 653, 27);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (28, 'Bread - Raisin', 'Incis cx to assist deliv', false, 6.6, 671, 28);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (29, 'Flavouring - Rum', 'Eye fluorescein angiogra', false, 35.3, 617, 29);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (30, 'Tarts Assorted', 'Removal of FB NOS', false, 36.3, 827, 30);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (31, 'Cheese - Mozzarella, Buffalo', 'Closed brain biopsy', true, 41.9, 725, 31);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (32, 'Blueberries', 'Biliary tract x-ray NEC', true, 45.5, 518, 32);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (33, 'Corn - Mini', 'Hip surface, cermc/cermc', true, 47.9, 532, 33);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (34, 'Doilies - 12, Paper', 'Transab cerclage cervix', false, 21.5, 867, 34);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (35, 'Mix - Cocktail Ice Cream', 'Exc maj les lid ful-thic', true, 6.6, 844, 35);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (36, 'Lid Coffee Cup 8oz Blk', 'Suture anal laceration', false, 3.9, 858, 36);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (37, 'Dill Weed - Dry', 'Local renal perfusion', false, 1.6, 783, 37);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (38, 'Lid - 10,12,16 Oz', 'Pericolost hernia repair', true, 49.8, 722, 38);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (39, 'Langers - Cranberry Cocktail', 'Pineal gland incision', true, 10.4, 643, 39);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (40, 'Cheese - Gouda', 'Carotid pulse tracing', true, 30.9, 517, 40);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (41, 'Dome Lid Clear P92008h', 'Fallop tube repair NEC', false, 34.4, 977, 41);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (42, 'Longos - Chicken Wings', 'Canaliculus repair', false, 48.2, 521, 42);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (43, 'Soup - Campbells Beef Stew', 'Thor vessel resect/anast', false, 49.5, 989, 43);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (44, 'Ice Cream - Chocolate', 'Pros rep ventrc def-clos', true, 27.5, 671, 44);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (45, 'Goat - Leg', 'Lam keratplast w autgrft', false, 1.5, 592, 45);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (46, 'Beef - Tender Tips', 'Instrument delivery NEC', true, 8.6, 519, 46);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (47, 'Cookies Oatmeal Raisin', 'Ing hernia rep-graft NOS', true, 40.9, 790, 47);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (48, 'Lettuce - Romaine', 'Hysterectomy NEC/NOS', false, 33.0, 521, 48);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (49, 'Cheese - La Sauvagine', 'Pyeloscopy', true, 36.8, 710, 49);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (50, 'Energy Drink - Franks Original', 'Open reduct face fx NEC', true, 33.0, 864, 50);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (51, 'Bar - Sweet And Salty Chocolate', 'Lung transplant NOS', true, 2.9, 763, 51);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (52, 'Eggwhite Frozen', 'Aortocor bypas-3 cor art', false, 31.6, 863, 52);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (53, 'Squid - U 5', 'Carotid pulse tracing', false, 1.2, 614, 53);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (54, 'Swordfish Loin Portions', 'Open fx site debride NEC', true, 48.3, 926, 54);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (55, 'Beans - Yellow', 'Thoracic duct fistulizat', true, 37.6, 847, 55);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (56, 'Bag Clear 10 Lb', 'Electrocoag rect les NEC', false, 38.6, 760, 56);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (57, 'Bread - Assorted Rolls', 'Oth metac/carp rep/plast', true, 25.6, 800, 57);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (58, 'Apple - Delicious, Red', 'Opn bi dr/in ing hrn NEC', false, 27.2, 649, 58);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (59, 'Flour - Pastry', 'Coronary arteriogram NEC', false, 46.1, 715, 59);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (60, 'Mushroom - Chantrelle, Fresh', 'Activ musculosk exer NEC', false, 11.2, 524, 60);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (61, 'Currants', 'Closed pulmon valvotomy', true, 12.5, 922, 61);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (62, 'Ice Cream Bar - Hageen Daz To', 'Wide excision of lip les', true, 30.2, 867, 62);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (63, 'Cookies - Assorted', 'Xtraoc mus op/detach NEC', true, 1.3, 836, 63);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (64, 'Chestnuts - Whole,canned', 'Limited consultation', false, 22.9, 707, 64);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (65, 'Compound - Mocha', 'Intravascul imaging NOS', false, 48.7, 950, 65);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (66, 'Sugar - Brown, Individual', 'Lap umbil hernia-graft', false, 39.4, 985, 66);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (67, 'Cheese - Cottage Cheese', 'Lid marg recon-part thic', true, 20.9, 980, 67);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (68, 'Wine - White, Lindemans Bin 95', 'Oth lo vision aid dispen', true, 35.4, 616, 68);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (69, 'Pastry - French Mini Assorted', 'Cell blk/pap-musculoskel', false, 11.5, 727, 69);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (70, 'Pepper - Black, Crushed', 'Adrenal lesion excision', true, 12.8, 685, 70);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (71, 'Cheese - Cheddar, Mild', 'Arterial bld gas measure', true, 29.4, 854, 71);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (72, 'Food Colouring - Red', 'D & C for preg terminat', true, 23.5, 854, 72);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (73, 'Turkey - Oven Roast Breast', 'Thorac esophagoenter NEC', false, 33.8, 802, 73);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (74, 'Wine - Placido Pinot Grigo', 'Sing source radiosurgery', true, 43.1, 535, 74);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (75, 'Cake - Miini Cheesecake Cherry', 'Soft tissue dx proc NEC', false, 4.4, 844, 75);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (76, 'Cookie Dough - Oatmeal Rasin', 'Destruct mediastin les', false, 46.8, 525, 76);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (77, 'Appetizer - Chicken Satay', 'Other destru pancrea les', false, 45.6, 656, 77);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (78, 'V8 - Berry Blend', 'Repair vess w tis patch', true, 9.8, 939, 78);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (79, 'Persimmons', 'Hip surface, metal/metal', false, 23.4, 781, 79);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (80, 'Beef - Bones, Marrow', 'Insert 1 vascular stent', false, 20.4, 839, 80);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (81, 'Magnotta - Bel Paese White', 'Excise bone for grft NOS', true, 5.4, 833, 81);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (82, 'Pizza Pizza Dough', 'Thymus biopsy', false, 10.0, 611, 82);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (83, 'Alize Sunset', 'Unil breast injec-augmen', true, 45.8, 655, 83);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (84, 'Wine - Malbec Trapiche Reserve', 'Perc abltn liver les/tis', true, 21.2, 610, 84);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (85, 'Beer - True North Strong Ale', 'After-cataract excision', false, 42.2, 509, 85);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (86, 'Lamb - Whole Head Off', 'Lap indir ing hern-graft', true, 1.4, 858, 86);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (87, 'Vacuum Bags 12x16', 'Tongue operation NEC', false, 32.7, 696, 87);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (88, 'Salami - Genova', 'Total hepatectomy', true, 37.8, 868, 88);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (89, 'Pastry - French Mini Assorted', 'Lap gastric restric proc', true, 33.8, 846, 89);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (90, 'Macaroons - Homestyle Two Bit', 'Insert ves-to-ves cannul', true, 11.7, 890, 90);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (91, 'Squash - Guords', 'Thumb reconstruction NEC', true, 4.6, 502, 91);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (92, 'Pop Shoppe Cream Soda', 'Eye/orbit inj repair NEC', true, 10.8, 728, 92);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (93, 'Appetizer - Assorted Box', 'Culture-blood', false, 34.5, 866, 93);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (94, 'Brownies - Two Bite, Chocolate', 'Micro exam-musculosk NEC', true, 21.8, 826, 94);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (95, 'Longan', 'Control of epistaxis NOS', false, 32.2, 502, 95);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (96, 'The Pop Shoppe Pinapple', 'Repair of spleen', false, 34.8, 899, 96);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (97, 'Sesame Seed Black', 'Conjunctivocystorhinost', false, 32.8, 983, 97);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (98, 'Meldea Green Tea Liquor', 'Gas hysterosalpingogram', true, 3.0, 800, 98);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (99, 'Tomato - Peeled Italian Canned', 'Endosc sm bowel thru st', false, 32.2, 891, 99);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (100, 'Dasheen', 'Suture penile laceration', true, 28.1, 859, 100);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (101, 'Sandwich Wrap', 'Contr semin vesiculogram', false, 34.6, 622, 101);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (102, 'Quail - Jumbo', 'Periph nerve dx proc NEC', false, 29.4, 941, 102);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (103, 'Soup - Knorr, Chicken Gumbo', 'Repair of cleft lip', true, 40.0, 933, 103);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (104, 'Wine - Rhine Riesling Wolf Blass', 'Radioisot teleradiother', true, 16.1, 637, 104);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (105, 'Pate - Liver', 'C & s NEC', true, 38.3, 872, 105);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (106, 'Ginger - Pickled', 'Reclose post op disrupt', true, 10.1, 747, 106);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (107, 'Chives - Fresh', 'Remov intralum vag FB', true, 40.9, 669, 107);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (108, 'Energy Drink - Franks Original', 'Transureteroureterostomy', true, 37.2, 569, 108);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (109, 'Plasticforkblack', 'High-dose infusion IL-2', false, 31.0, 960, 109);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (110, 'Hog / Sausage Casing - Pork', 'Other muscle transposit', true, 35.9, 609, 110);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (111, 'Syrup - Monin, Amaretta', 'Temp detach >1 xtroc mus', true, 32.8, 567, 111);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (112, 'Cape Capensis - Fillet', 'Limb lengthn-metatar/tar', false, 43.2, 942, 112);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (113, 'Ice Cream - Strawberry', 'Excis ampulla of vater', true, 37.1, 580, 113);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (114, 'Bread - Pain Au Liat X12', 'Dental x-ray NEC', true, 4.7, 507, 114);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (115, 'Spinach - Baby', 'Keratomileusis', false, 25.5, 874, 115);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (116, 'Wine - Rosso Toscano Igt', 'Inc soft tissue hand NEC', false, 2.7, 951, 116);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (117, 'Shrimp - 31/40', 'Bilat adrenal explorat', true, 11.7, 897, 117);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (118, 'Wine - Lou Black Shiraz', 'Int fix-no fx reduct NEC', false, 14.0, 502, 118);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (119, 'Canada Dry', 'Cervical lymphangiogram', false, 2.1, 981, 119);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (120, 'Banana - Green', 'Myelomeningocel repair', false, 36.3, 799, 120);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (121, 'Pepper - Chillies, Crushed', 'Five-in-one knee repair', false, 4.3, 666, 121);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (122, 'Pepper - Green Thai', 'Lung laceration closure', true, 19.8, 592, 122);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (123, 'Onion - Dried', 'Lac canaliculi incision', true, 17.1, 848, 123);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (124, 'Turkey - Oven Roast Breast', 'Periprostatic incision', true, 9.0, 516, 124);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (125, 'Pork - Sausage Casing', 'Cell blk/pap-integument', false, 40.2, 863, 125);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (126, 'Mints - Striped Red', 'Renal repair NEC', false, 16.3, 761, 126);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (127, 'Pasta - Fusili, Dry', 'Ext maxillary antrot NEC', false, 24.8, 513, 127);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (128, 'Wood Chips - Regular', 'Other therapeutic ultsnd', true, 33.9, 633, 128);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (129, 'Initation Crab Meat', 'Excision of lip les NEC', false, 14.4, 564, 129);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (130, 'V8 Pet', 'Nephrocystanastomosi NOS', false, 17.5, 523, 130);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (131, 'Crab - Meat Combo', 'Labial frenotomy', true, 16.3, 561, 131);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (132, 'Eggplant - Regular', 'Rad dissec periaort node', false, 48.2, 955, 132);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (133, 'Oats Large Flake', 'Destruct facial bone les', false, 21.7, 527, 133);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (134, 'Carbonated Water - White Grape', 'Partial esophagectomy', false, 24.9, 568, 134);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (135, 'Lettuce - Sea / Sea Asparagus', 'Lower leg/ankle reattach', true, 15.1, 827, 135);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (136, 'Veal - Bones', 'Patellar stabilization', false, 23.0, 954, 136);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (137, 'Vinegar - Champagne', 'Exc of accessory spleen', true, 20.1, 966, 137);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (138, 'Doilies - 10, Paper', 'Reopen craniotomy site', true, 2.5, 524, 138);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (139, 'Rosemary - Primerba, Paste', 'Exploratory thoracotomy', true, 14.8, 713, 139);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (140, 'Chips Potato Salt Vinegar 43g', 'Excis les lacrimal gland', false, 23.2, 993, 140);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (141, 'Sea Bass - Whole', 'Vital capacity determin', false, 40.1, 902, 141);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (142, 'Loquat', 'Pericardial biopsy', true, 7.1, 754, 142);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (143, 'Wine - Chablis J Moreau Et Fils', 'Pancreatic operation NEC', true, 47.4, 546, 143);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (144, 'Trout - Hot Smkd, Dbl Fillet', 'Bone graft NOS', false, 44.5, 612, 144);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (145, 'Herb Du Provence - Primerba', 'Oth lap loc exc dest ova', false, 7.9, 602, 145);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (146, 'Tray - 12in Rnd Blk', 'Comprehensive consultat', false, 19.7, 612, 146);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (147, 'Butcher Twine 4r', 'Opn/oth part gastrectomy', true, 21.3, 844, 147);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (148, 'Artichokes - Jerusalem', 'Conduit left ventr-aorta', false, 30.6, 972, 148);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (149, 'Stock - Beef, Brown', 'Nasal fistula closure', false, 6.4, 655, 149);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (150, 'Ice Cream - Super Sandwich', 'Suture breast laceration', true, 3.5, 966, 150);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (151, 'Crab Brie In Phyllo', 'Impl other limb length', false, 22.7, 969, 151);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (152, 'Tofu - Firm', 'Sialoadenectomy NOS', false, 20.7, 664, 152);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (153, 'Ginger - Crystalized', 'Oth laryngeal operation', false, 23.4, 966, 153);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (154, 'Mangostein', 'Intra-amnion inj for ab', false, 7.1, 918, 154);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (155, 'Goldschalger', 'Percutaneous angioscopy', false, 2.6, 808, 155);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (156, 'Pastry - Plain Baked Croissant', 'Choledochoenterostomy', true, 20.5, 576, 156);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (157, 'Kumquat', 'Local sm bowel perfusion', true, 18.2, 729, 157);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (158, 'Beef - Bones, Marrow', 'Intra-abd venous shunt', false, 33.9, 613, 158);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (159, 'Cookie Dough - Double', 'Lacrimal sys dx proc NEC', true, 45.4, 769, 159);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (160, 'Chickensplit Half', 'Removal of cement spacer', false, 40.2, 655, 160);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (161, 'Soup - Campbells Tomato Ravioli', 'Other CAS', true, 49.9, 724, 161);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (162, 'Cardamon Ground', 'Corneal repair NEC', true, 40.9, 990, 162);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (163, 'Pasta - Fett Alfredo, Single Serve', 'Lid reconst w skin graft', false, 49.3, 710, 163);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (164, 'Hersey Shakes', 'Limb lengthn-metatar/tar', false, 10.2, 883, 164);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (165, 'V8 - Berry Blend', 'Aortcor bypas-4+ cor art', false, 46.5, 599, 165);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (166, 'Wine - Cava Aria Estate Brut', 'Syndactyly correction', false, 4.1, 998, 166);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (167, 'Coffee - Almond Amaretto', 'Anal fistulotomy', true, 21.0, 661, 167);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (168, 'Wine - Red, Gamay Noir', 'Suture tendn sheath hand', true, 1.5, 856, 168);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (169, 'Pastry - Key Limepoppy Seed Tea', 'Wound catheter irrigat', false, 7.5, 584, 169);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (170, 'Spinach - Spinach Leaf', 'Contr thor arteriogr NEC', false, 2.6, 693, 170);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (171, 'Aspic - Amber', 'Remove dental prosthesis', true, 29.2, 523, 171);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (172, 'Bread Country Roll', 'Limb shorten-tib/fibula', true, 26.1, 906, 172);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (173, 'Cake - Pancake', 'Destruct abd wall lesion', true, 49.7, 842, 173);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (174, 'Coffee - Almond Amaretto', 'Sutur capsul/ligamen arm', false, 34.0, 935, 174);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (175, 'Fruit Salad Deluxe', 'Spermatic cord incision', false, 31.7, 998, 175);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (176, 'True - Vue Containers', 'Bladder diagnos proc NEC', false, 30.4, 713, 176);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (177, 'Sugar - Fine', 'Cystotomy NEC', true, 47.6, 922, 177);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (178, 'Flour - Bread', 'Manual exam of breast', true, 11.7, 709, 178);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (179, 'Loaf Pan - 2 Lb, Foil', 'Revision of tracheostomy', false, 8.7, 796, 179);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (180, 'Pork - Loin, Bone - In', 'Arterial catheterization', false, 32.0, 954, 180);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (181, 'Cookie Trail Mix', 'Skel xray-upper limb NOS', false, 47.6, 982, 181);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (182, 'Soap - Mr.clean Floor Soap', 'Replace indwelling cath', false, 24.2, 624, 182);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (183, 'Dooleys Toffee', 'Radical prostatectomy', false, 43.6, 807, 183);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (184, 'Shrimp - 16/20, Peeled Deviened', 'Retrogr cystourethrogram', false, 49.9, 787, 184);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (185, 'Tomato - Green', 'Sm bowel exteriorization', true, 37.6, 879, 185);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (186, 'Goulash Seasoning', 'Open red-sep epiphy NOS', true, 9.8, 809, 186);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (187, 'Wine - Niagara Peninsula Vqa', 'Loc exc les metatar/tar', false, 16.9, 910, 187);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (188, 'Sugar - Individual Portions', 'Hand muscle reattachment', true, 7.9, 592, 188);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (189, 'Olives - Morracan Dired', 'Contrast laryngogram', false, 32.4, 856, 189);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (190, 'Pomello', 'Chorioret les destr NEC', false, 29.3, 921, 190);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (191, 'Wine - Sake', 'Eye examination NOS', true, 17.2, 641, 191);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (192, 'Langers - Cranberry Cocktail', 'Pros rep ventrc def-clos', true, 1.4, 874, 192);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (193, 'Cherries - Bing, Canned', 'Chest wall biopsy', true, 47.1, 803, 193);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (194, 'Beans - Yellow', 'Injection of larynx', false, 23.9, 786, 194);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (195, 'Dasheen', 'Clos mediastinal biopsy', false, 12.1, 867, 195);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (196, 'Raspberries - Fresh', 'Periph nerve div NEC', true, 48.5, 581, 196);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (197, 'Extract - Raspberry', 'Endosc remove panc stone', false, 43.8, 520, 197);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (198, 'Juice - Clamato, 341 Ml', 'Skull x-ray NEC', true, 26.2, 699, 198);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (199, 'Wine - Chablis J Moreau Et Fils', 'Closed biopsy of tongue', false, 4.1, 736, 199);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (200, 'Bread - Corn Muffaleta Onion', 'Tendon reattachment', true, 36.5, 728, 200);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (201, 'Cornflakes', 'Hepatic injection NEC', true, 26.7, 555, 201);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (202, 'Cheese - Provolone', 'Other repair of joint', false, 48.7, 567, 202);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (203, 'Lemonade - Pineapple Passion', 'Reimplan aberr renal ves', false, 6.6, 997, 203);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (204, 'Venison - Ground', 'Thoracic endarterectomy', false, 38.2, 846, 204);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (205, 'Roe - Lump Fish, Red', 'Unilat thyroid lobectomy', false, 38.6, 547, 205);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (206, 'Eel Fresh', 'Lap appendectomy', true, 42.4, 746, 206);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (207, 'Sauce - Soya, Light', 'Excision thyroid lesion', true, 30.3, 549, 207);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (208, 'Food Colouring - Pink', 'Other tenoplasty of hand', true, 26.9, 647, 208);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (209, 'Juice - Pineapple, 341 Ml', 'Therapeu erythropheresis', false, 23.4, 753, 209);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (210, 'Filling - Mince Meat', 'Revise sm bowel anastom', true, 14.2, 816, 210);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (211, 'V8 - Tropical Blend', 'Cell blk/pap-lymph sys', true, 6.4, 946, 211);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (212, 'Beer - Tetleys', 'Oth endo proc oth vessel', false, 9.1, 891, 212);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (213, 'Bread - Bistro White', 'Wrist synovectomy', true, 11.9, 966, 213);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (214, 'Drambuie', 'Unilat adrenal explorat', true, 9.4, 918, 214);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (215, 'Nut - Pistachio, Shelled', 'Cde for obstruction NEC', false, 40.3, 836, 215);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (216, 'Cookie - Dough Variety', 'Part breech extract NEC', true, 18.3, 664, 216);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (217, 'Persimmons', 'Cruciate lig repair NEC', true, 25.4, 597, 217);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (218, 'Pop - Club Soda Can', 'Total elbow replacement', false, 7.3, 540, 218);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (219, 'Nori Sea Weed - Gold Label', 'Intravasc msmnt cor art', false, 49.4, 636, 219);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (220, 'Cheese - Havarti, Roasted Garlic', 'Closed pulmon valvotomy', true, 4.7, 798, 220);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (221, 'Flax Seed', 'Urinary manometry', false, 47.9, 917, 221);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (222, 'Swordfish Loin Portions', 'Remove bile duct prosth', false, 32.4, 656, 222);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (223, 'Icecream Cone - Areo Chocolate', 'Retroperitoneal xray NEC', false, 3.0, 931, 223);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (224, 'Chicken - Ground', 'Pass musculosk exer NEC', false, 13.3, 621, 224);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (225, 'Sauce - Hp', 'Finger reattachment', true, 24.6, 633, 225);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (226, 'Sambuca Cream', 'Manual reduc rect prolap', true, 29.0, 842, 226);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (227, 'Milk - Chocolate 500ml', 'Thyroid field aspiration', true, 27.1, 819, 227);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (228, 'Oven Mitts - 15 Inch', 'Part gast w jej transpos', false, 37.4, 798, 228);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (229, 'Potato - Sweet', 'Oth plastic repair palat', true, 47.7, 639, 229);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (230, 'Country Roll', 'Other plastic ops muscle', true, 39.8, 643, 230);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (231, 'Lentils - Green Le Puy', 'Rep vaginoent fistul NEC', true, 19.8, 620, 231);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (232, 'Salmon - Atlantic, Fresh, Whole', 'Remov imp dev-tib/fibula', true, 26.4, 987, 232);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (233, 'Pasta - Angel Hair', 'Tympanosympathectomy', false, 7.8, 716, 233);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (234, 'Bread - Rosemary Focaccia', 'Open periph nerve biopsy', false, 23.2, 572, 234);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (235, 'Hipnotiq Liquor', 'Culdocentesis', true, 29.3, 772, 235);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (236, 'Hand Towel', 'Micro exam-periton NEC', true, 2.6, 736, 236);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (237, 'Pepper - Jalapeno', 'Oth extraoc mus-tend op', false, 33.2, 905, 237);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (238, 'Grand Marnier', 'Other arthrotomy NOS', true, 37.0, 851, 238);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (239, 'Bread - Dark Rye, Loaf', 'Parasitology-lower GI', true, 42.7, 947, 239);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (240, 'Bagel - Sesame Seed Presliced', 'Rev knee replace-patella', true, 4.2, 944, 240);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (241, 'Extract - Rum', 'Intravascul imaging NEC', false, 44.0, 825, 241);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (242, 'Brownies - Two Bite, Chocolate', 'Partial splenectomy', true, 26.7, 887, 242);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (243, 'Tomatillo', 'Electroencephalogram', false, 15.6, 993, 243);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (244, 'Wine - Shiraz South Eastern', 'Ext carot art lig-epist', false, 49.0, 507, 244);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (245, 'Pasta - Agnolotti - Butternut', 'Oth unilat oophorectomy', false, 18.0, 581, 245);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (246, 'Lid - 3oz Med Rec', 'Adjust gast restrict dev', true, 14.7, 621, 246);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (247, 'Venison - Ground', 'Other tenoplasty of hand', false, 33.9, 676, 247);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (248, 'Wine - Saint - Bris 2002, Sauv', 'Toxicology-blood', false, 30.4, 963, 248);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (249, 'Wine - White, Pinot Grigio', 'Transposit hand tend NEC', true, 27.7, 995, 249);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (250, 'Godiva White Chocolate', 'Therapeutc photopheresis', true, 9.0, 626, 250);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (251, 'Butter - Pod', 'Oth arthrotomy-hip', true, 21.4, 652, 251);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (252, 'Butter Balls Salted', 'Skin closure NEC', true, 45.0, 735, 252);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (253, 'Muffin - Mix - Creme Brule 15l', 'Lacrimal sys dx proc NEC', false, 12.8, 742, 253);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (254, 'Octopus', 'Bact smear-eye', true, 21.1, 858, 254);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (255, 'Sugar - Sweet N Low, Individual', 'Int fix w/o fx reduc NOS', false, 3.3, 730, 255);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (256, 'Sugar - Brown', 'Conjunctival biopsy', false, 34.8, 761, 256);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (257, 'Scallops - U - 10', 'Facial bone x-ray NEC', false, 33.2, 859, 257);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (258, 'Pepper - Chilli Seeds Mild', 'Tot brch extrac w forcep', false, 35.8, 600, 258);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (259, 'Sauce - Alfredo', 'Decortication of lung', false, 48.2, 850, 259);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (260, 'Oil - Sunflower', 'TRAM flap, pedicled', true, 11.3, 959, 260);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (261, 'Creme De Banane - Marie', 'Dx ultrasound-thorax NEC', true, 7.4, 531, 261);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (262, 'Garlic - Peeled', 'Extracorpor hepat Assis', false, 32.6, 565, 262);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (263, 'Chocolate - Sugar Free Semi Choc', 'Complete thyroidectomy', true, 39.0, 518, 263);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (264, 'Sauce - Vodka Blush', 'Replantation of penis', false, 38.3, 600, 264);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (265, 'Pomegranates', 'Whole blood transfus NEC', true, 12.2, 670, 265);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (266, 'Onions - Cippolini', 'Retinal tear laser coag', true, 23.0, 855, 266);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (267, 'Ice Cream - Strawberry', 'Excision of ankle NEC', true, 26.0, 603, 267);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (268, 'Bread Base - Toscano', 'Extended ophthal work-up', false, 29.9, 744, 268);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (269, 'Cake - Lemon Chiffon', 'Metatars/tars inj op NOS', true, 48.7, 534, 269);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (270, 'Wine - Chardonnay South', 'Lap bi indir ing hrn-grf', false, 12.2, 692, 270);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (271, 'Soup - Campbells Broccoli', 'Vaginoscopy', false, 39.8, 679, 271);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (272, 'Tomatoes - Grape', 'Separat unequl join twin', false, 40.0, 741, 272);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (273, 'Cheese - Comte', 'Open reduct maxillary fx', true, 17.2, 862, 273);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (274, 'Peas - Frozen', 'Rev crtd sinus stm leads', false, 29.3, 936, 274);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (275, 'Knife Plastic - White', 'Opn reduc disloc-shouldr', false, 41.1, 947, 275);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (276, 'Bread - Raisin', 'Bone biopsy NEC', true, 22.7, 948, 276);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (277, 'Cheese - Brick With Onion', 'Remov thorax sutures', false, 43.2, 967, 277);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (278, 'Mushroom - Chanterelle, Dry', 'Remov trunk device NEC', true, 45.3, 647, 278);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (279, 'Wine - White, Concha Y Toro', 'Auto hem stem ct w purg', true, 43.1, 559, 279);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (280, 'Energy - Boo - Koo', 'Remove spine theca shunt', false, 27.6, 917, 280);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (281, 'Carbonated Water - Blackcherry', 'Partial ventriculectomy', false, 37.2, 559, 281);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (282, 'Wine - Rosso Toscano Igt', 'Esophageal repair NEC', false, 6.3, 837, 282);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (283, 'Hickory Smoke, Liquid', 'Sphinct of oddi measure', true, 42.3, 878, 283);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (284, 'Muffin Puck Ww Carrot', 'Bact smear-nervous syst', false, 48.3, 810, 284);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (285, 'Wine - Alicanca Vinho Verde', 'Aspiration of bursa', false, 7.0, 983, 285);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (286, 'Bandage - Flexible Neon', 'Intravasclr spectroscopy', true, 6.1, 952, 286);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (287, 'Carrots - Jumbo', 'Limb lengthen proc NOS', true, 29.8, 744, 287);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (288, 'Bread - Bistro White', 'Cerebral thermography', false, 7.9, 873, 288);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (289, 'Pork - Loin, Bone - In', 'Cl red-int fix rad/ulna', true, 38.6, 895, 289);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (290, 'Cheese - Sheep Milk', 'Suppor verbal psychother', false, 8.4, 652, 290);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (291, 'Beets', 'Operation on lens NEC', false, 26.4, 936, 291);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (292, 'Pastry - Mini French Pastries', 'Consultation NEC', false, 38.8, 949, 292);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (293, 'Crab - Dungeness, Whole', 'Renal scan/isotope funct', false, 48.5, 820, 293);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (294, 'Lamb - Shanks', 'Urethrotomy', true, 7.0, 924, 294);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (295, 'Goulash Seasoning', 'Nasophary contrast x-ray', true, 38.5, 531, 295);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (296, 'Plasticspoonblack', 'Lap umbilical hernia NEC', true, 18.3, 512, 296);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (297, 'Tomatoes - Diced, Canned', 'Intranasal antrotomy', false, 37.9, 517, 297);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (298, 'Chicken - White Meat With Tender', 'Other group therapy', false, 22.2, 786, 298);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (299, 'Juice - Prune', 'Tot brch extrac w forcep', false, 48.9, 956, 299);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (300, 'Plate Pie Foil', 'Remov intralum esoph FB', true, 25.8, 867, 300);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (301, 'Chicken - Base', 'Contrast vasogram', true, 44.8, 513, 301);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (302, 'Ranchero - Primerba, Paste', 'Imp cardiomyostimul sys', true, 5.3, 646, 302);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (303, 'Dc Hikiage Hira Huba', 'Part sm bowel resect NEC', false, 42.9, 537, 303);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (304, 'Mushroom - Shitake, Fresh', 'Dressing of wound NEC', true, 14.1, 540, 304);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (305, 'Pork - Suckling Pig', 'Mobilization of spine', false, 15.6, 863, 305);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (306, 'Bread Cranberry Foccacia', 'Drsl/drslumb fus ant/ant', true, 11.8, 573, 306);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (307, 'Thyme - Fresh', 'Vulvar adhesiolysis', true, 1.7, 545, 307);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (308, 'Bread - Dark Rye', 'Repl pacem w dual-cham', false, 38.0, 583, 308);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (309, 'Propel Sport Drink', 'Replace wound pack/drain', true, 19.0, 518, 309);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (310, 'Nut - Chestnuts, Whole', 'Urethral biopsy', true, 12.8, 561, 310);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (311, 'Salmon - Canned', 'Skel xray-elbow/forearm', true, 18.9, 630, 311);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (312, 'Versatainer Nc - 9388', 'Destruct joint les NOS', true, 12.3, 841, 312);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (313, 'Sprouts - Bean', 'Crown application', false, 22.4, 968, 313);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (314, 'Wine - Two Oceans Cabernet', 'Iris operation NEC', true, 4.7, 684, 314);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (315, 'Nut - Almond, Blanched, Whole', 'Auto hem stem ct w purg', false, 8.9, 759, 315);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (316, 'Stock - Chicken, White', 'Prosth rep hrt septa NOS', true, 7.2, 547, 316);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (317, 'Sauce - Hp', 'Suture vagina laceration', true, 37.8, 953, 317);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (318, 'Nut - Peanut, Roasted', 'Ather oth non-cor vessel', true, 6.6, 952, 318);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (319, 'Lemonade - Pineapple Passion', 'Totl reconstc breast NOS', false, 37.6, 572, 319);
insert into producto (id_product, name_product, desc_product, dangerous, kg, cant, id_transport) values (320, 'Bread - Onion Focaccia', 'Metacarpal/carpal biopsy', false, 33.9, 856, 320);
